/* Replace with your SQL commands */
DROP SCHEMA IF EXISTS lb CASCADE;
CREATE SCHEMA lb;
GRANT ALL ON SCHEMA lb TO public;

CREATE SEQUENCE lb.users_id_seq START WITH 1;

CREATE TABLE lb.users (
  id                   integer  NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	first_name           varchar(50)  NOT NULL,
	last_name            varchar(50),
	username             varchar(150)  NOT NULL,
	email                varchar(150),
	password             varchar(60)  NOT NULL,
	permissions          varchar(60)[],
	deleted              bool DEFAULT false NOT NULL,
	deleted_on           timestamptz,
	deleted_by           integer,

	CONSTRAINT pk_user_id PRIMARY KEY ( id ),
	CONSTRAINT idx_username UNIQUE ( username )
)